# Generated by Django 5.2.5 on 2025-08-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_classmodel_alter_teachermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
