# Generated by Django 5.2.5 on 2025-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_studentmodel_name_teachermodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='user',
            new_name='username',
        ),
    ]
